version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: alisha
      MONGO_INITDB_ROOT_PASSWORD: "1234"
    volumes:
      - mongo_data:/data/db
    networks:
      - test-network

networks:
  test-network:
    external: true

volumes:
  mongo_data:
